language: java

matrix:
  include:
    - jvm: "6"
    - jvm: "7"
    - jvm: "8"
    - jvm: "10"
#    - jdk: openjdk8
#      addons:
#        apt:
#          packages:
#            - openjdk-6-jdk

before_script: export && echo invoking before script, build directory: $TRAVIS_BUILD_DIR
script: echo $TRAVIS_BUILD_DIR && mvn clean package -DskipDocs -s "$TRAVIS_BUILD_DIR/maven_settings_for_travisci.xml"


git:
  quiet: true
branches:
  only:
    - master

notifications:
  slack:
    on_success: always
  email:
    recipients:
      - fs1194361820@163.com
    on_success: never
    on_failure: always

