language: java

matrix:
  include:
    - jdk: oraclejdk8
    - jdk: openjdk7
    - jdk: openjdk8
    - jdk: openjdk10
    - jdk: openjdk8
#      addons:
#        apt:
#          packages:
#            - openjdk-6-jdk

script: echo $TRAVIS_BUILD_DIR && mvn clean package -DskipDocs -s "$TRAVIS_BUILD_DIR/maven_settings_for_travisci.xml"


git:
  quiet: true
branches:
  only:
    - master

notifications:
  slack:
    on_success: always
  email:
    recipients:
      - fs1194361820@163.com
    on_success: never
    on_failure: always

