language: java
addons:
  apt:
    packages:
      - openjdk-6-jdk

jdk:
  - oraclejdk8
  - openjdk6
  - openjdk7
  - openjdk8
  - openjdk10
git:
  quiet: true
branches:
  only:
    - master

notifications:
  slack:
    on_success: always
  email:
    recipients:
      - fs1194361820@163.com
    on_success: never
    on_failure: always

before_script: export && echo invoking before script, build directory: $TRAVIS_BUILD_DIR
script: echo $TRAVIS_BUILD_DIR && mvn clean package -DskipDocs -s "$TRAVIS_BUILD_DIR/maven_settings_for_travisci.xml"

